### PR TITLE
Move fixtures to common

### PR DESCRIPTION
**Pull request by saidelike**
## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

This is to prepare other IDE like neovim to use fixtures. I confirmed all the tests passed. `7189 passing (4m)`. I fixed the references in the documentation.

### CODE REVIEW

**Comment by pokey** [comment]
Hmm, not sure common is where these belong. Maybe test harness? Cc/ @AndreasArvidsson any opinion here?

**Comment by saidelike** [comment]
Then it would mean cursorless-neovim needs to depend on test harness too?

**Comment by pokey** [comment]
They're just static fixtures, so not sure there needs to be a dependency? TBH we could move them out of packages dir altogether

**Comment by saidelike** [comment]
Ya probably makes sense to move them to "cursorless/fixtures" then?

**Comment by AndreasArvidsson** [comment]
> Hmm, not sure common is where these belong. Maybe test harness? Cc/ @AndreasArvidsson any opinion here?

I agree that they probably do not belong in common. Either in test harness or in a new fixtures folder sounds fine to me.

**Comment by saidelike** [comment]
Deprecated by https://github.com/cursorless-dev/cursorless/pull/2276

**Pull request closed without merging**
