### PR TITLE
Add randomizeTargets action

### PR DESCRIPTION
**Pull request by alexhwoods**
Addresses https://github.com/pokey/cursorless-vscode/issues/424

Let me know if I violated any API patterns that you guys use!

### CODE REVIEW

**Comment by alexhwoods** [comment]
https://user-images.githubusercontent.com/7907782/148776791-c23e7b05-a725-4863-a8b3-54f6ca0505f5.mp4

**Comment by alexhwoods** [comment]
cursorless-talon PR on the way!

**Review by pokey — COMMENTED** [review]
Looks great!  Please [add a test](https://github.com/pokey/cursorless-vscode/blob/main/docs/contributing/test-case-recorder.md) 😊.  You'll need to do something like [this](https://github.com/lodash/lodash/issues/3289#issuecomment-941264195) for determinism

**Comment by pokey** [comment]
As discussed, let's just settle for recording a test that shuffles a list with a single element

**Comment by AndreasArvidsson** [comment]
closed by #440

**Pull request closed without merging**
