### PR TITLE
Added support to split on dots in cheat sheet

### LINKED ISSUE #469: Fix regex in cheatsheet to handle dots
This is particularly important when the user has a custom command because the vscode commands use dots to separate

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
fixes #469

### CODE REVIEW

**Comment by AndreasArvidsson** [comment]
@pokey Shouldn't the vendor files be excluded from the linting test?

**Comment by pokey** [comment]
We could, but given it's such a trivial diff I'd be tempted to just run black on it for now 🤷

**Review by pokey — APPROVED** [review]

**Comment by AndreasArvidsson** [comment]
I already have. Running black on the file locally gives zero changes.

**Comment by pokey** [comment]
maybe need to update your black?  my hypothesis is that it's due to an update to black

**Comment by pokey** [comment]
looks like the black thing is fixed on #529 so maybe let's get that one in and then you can just rebase onto it

**Comment by AndreasArvidsson** [comment]
> looks like the black thing is fixed on #529 so maybe let's get that one in and then you can just rebase onto it

Sounds good

**Pull request merged**
